#!/bin/sh
#
# /usr/local/bin/email_attach
#
# Attach multiple files to an email

[ -r "$1" ] || exit 1
attachments="$1"
shift

while [ -r "$1" ]; do
	attachments="$attachments,$1"
	shift
done

thunderbird -compose attachment=$(printf "'%s'\n" "$attachments")
