#!/bin/sh

Status=$(cat /sys/class/drm/card0-HDMI-A-1/status)
if [ "$Status" == "connected" ]; then
#	pactl set-card-profile 0 output:hdmi-stereo+input:analog-stereo
	pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_3__sink
else
#	pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
	pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink
fi
