#!/bin/sh

Status=$(cat /sys/class/drm/card0-HDMI-A-1/status)
if [ "$Status" == "connected" ]; then
	pactl set-card-profile 0 output:hdmi-stereo+input:analog-stereo
else
    pactl set-card-profile 0 output:analog-stereo+input:analog-stereo
fi
