#!/bin/sh
#
# /usr/local/bin/music 
#
# Depends: mplayer, dmenu

# If mplayer is already running, echo commands to mp_pipe
if pgrep mplayer >/dev/null; then
    case "$1" in
        stop)   echo stop >~/.mplayer/mp_pipe && exit ;;
        prev)   echo pt_step -1 >~/.mplayer/mp_pipe && exit ;;
        next)   echo pt_step 1 >~/.mplayer/mp_pipe && exit ;;
        *)      echo pause >~/.mplayer/mp_pipe && exit ;;
    esac
fi

# Don't run if stop|prev|next key was pressed
[ "$1" ] && exit

# Cache files:
AlbumCache=~/.mplayer/album_cache
TrackCache=~/.mplayer/track_cache

if stest -dlq -n "$AlbumCache" ~/Music; then
    # Update caches if anything has changed:
    echo Jukebox >"$AlbumCache"
    stest -dl ~/Music | sort >>"$AlbumCache"
    stest -f ~/Music/*/* >"$TrackCache"
fi

# Select an album:
Album=$( cat "$AlbumCache" | dmenu -i -l 40 ) || exit

if [ "$Album" = Jukebox ]; then
    # Prompt for filters:
    Filters=$( printf "" | dmenu -p Filters? ) || exit

    if [ "$Filters" ]; then
        # Apply filters and shuffle tracks:
        set $( echo "$Filters" ) 
        while [ "$1" ]; do 
            grep -Fi "$1" "$TrackCache"
            shift
        done | mplayer -playlist - -shuffle -identify >/tmp/mp_tracklist &

    else
        # No filters, so shuffle all tracks:
        mplayer -playlist "$TrackCache" -shuffle -identify >/tmp/mp_tracklist &
    fi

else
    # Album is selected, prompt to play or shuffle:
    Mode=$( printf "Play\nShuffle" | dmenu -i -l 2 ) || exit

    if [ "$Mode" = Shuffle ]; then
        # Shuffle album tracks:
        mplayer ~/Music/"$Album"/* -shuffle -identify >/tmp/mp_tracklist &

    else
        # Play album in order:
        mplayer ~/Music/"$Album"/* -identify >/tmp/mp_tracklist &
    fi
fi

# Pause while mplayer starts:
sleep 1

# Loop while playing to store current track name:
while pgrep mplayer >/dev/null; do
    if [ ! /tmp/mp_tracklist -ot /tmp/mp_track ]; then
        tail -20 /tmp/mp_tracklist | awk -F "/" '/FILENAME/ { print $NF }' >/tmp/mp_track
    fi
    sleep 1
done

# Clean up afterwards:
rm /tmp/mp_track
rm /tmp/mp_tracklist 
