#!/bin/sh
#
# /usr/local/bin/open
#
# Depends: xpdf geeqie libreoffice


#case "$1" in
#    *.pdf|*.PDF)
#        xpdf "$1"
#    ;;
#
#    *.jpg|*.JPG|*.png|*.PNG|*.tiff|*.TIFF)
#        geeqie "$1"
#    ;;
#
#    *.doc|*.DOC|*.docx|*.DOCX|*.xls|*.XLS|*.ppt|*.PPT)
#        libreoffice "$1"
#    ;;
#
#easc

###### or ######

#File=$(file "$1")
#
#if echo "$File" | grep -Fq PDF; then
#    exec xpdf "$1"
#elif echo "$File" | grep -Fq image; then
#    exec geeqie "$1"
#elif echo "$File" | grep -Fq Document; then
#    exec libreoffice "$1"
#fi

###### or ######

while [ "$1"]; do
    echo $(file "$1") | \
        if grep -Fq PDF; then
            exec xpdf "$1"
        elif grep -Fq image; then
            exec geeqie "$1"
        elif grep -Fq Document; then
            exec libreoffice "$1"
        fi
    shift
done

# then add `shift' to process more arguments?..

