#!/bin/sh
#
# /usr/local/bin/open
#
# Depends: xpdf geeqie libreoffice


case "$1" in
    *.pdf|*.PDF)
        exec xpdf "$1"
        ;;

    *.jpg|*.JPG|*.png|*.PNG|*.tiff|*.TIFF)
        exec geeqie "$1"
        ;;

    *.doc|*.DOC|*.docx|*.DOCX|*.xls|*.XLS|*.xlsx|*.XLSX|*.dotx|*.DOTX|*.ppt|*.PPT|*.pptx|*.PPTX)
        exec libreoffice "$1"
        ;;

    *)
		exec mplayer "$1"
        ;;
esac

###### or ######

#File=$(file "$1")
#
#if echo "$File" | grep -Fq PDF; then
#    echo opening...
#    xpdf "$1" &
#elif echo "$File" | grep -Fq image; then
#    echo opening...
#    geeqie "$1" &
#elif echo "$File" | grep -Fq Document; then
#    echo opening...
#    libreoffice "$1" &
#elif echo "$File" | grep -Fq Rich; then
#    echo opening...
#    libreoffice "$1" &
#fi
