#!/bin/sh
#
# /usr/local/bin/photo_import_thunar
#
# Import photos from current directory, requires photo_rename and photo_sort

set -e

read -n1 -p "Do you want to import all pictures from this folder?
	(Press any key to continue or Ctrl-C to exit) "

Tempdir=$(mktemp -d ~/Pictures/tmp.XXXXXX)

for i in *.jpg *.JPG; do
	[ -f "$i" ] && cp -v "$i" $Tempdir
done

read -p "Do you want to delete all pictures from this folder?
	(Type yes if you do, otherwise press enter to keep pictures) "
[ "$REPLY" = yes ] && rm -f *.jpg *.JPG

cd $Tempdir
photo_rename
photo_sort

cd ~
rmdir $Tempdir 2>/dev/null && printf "\nDone\n\n" || \
	printf "\nSome photos still in %s\nto deal with manually\n\n" $Tempdir
read -n1 -p "Press any key to finish"
