#!/bin/sh
#
# /usr/local/bin/photo_video_sort
#
# Sort photos and videos into ~/Pictures/YYYY/MM/
# and hardlink videos into ~/Videos/

for i in 20*mp4 20*MP4; do
	[ -f "$i" ] && ln -v "$i" ~/Videos/
done

for i in 20*; do
	Name=$(basename "$i")
	Year="${Name:0:4}"
	Month="${Name:4:2}"
	case $Year in
		20[0-9][0-9])           ;;
		*)             continue ;;
	esac	
	case $Month in
		[0-1][0-9])             ;;
		*)             continue ;;
	esac	
	mkdir -p ~/Pictures/$Year/$Month
	mv -nv "$i" ~/Pictures/$Year/$Month/
done
