#!/bin/sh
#
# /usr/local/bin/photo_shrink
#
# Thunar custom action to shrink photos

shopt -s nullglob

for i in *.jpg; do
	convert "$i" -resize 1000 "${i/.jpg/-mini.jpg}"
	shift
done

for i in *.JPG; do
	convert "$i" -resize 1000 "${i/.JPG/-mini.jpg}"
	shift
done
