#!/bin/sh
#
# /usr/local/bin/photo_import
#
# Import media from camera
#
# Requires: photo_rename video_rename photo_video_sort

Camera=$(gphoto2 --auto-detect | sed -n 3p)

case $Camera in
	"")
		read -n1 -p "No camera connected. Press any key to exit"
		exit
		;;
	*Canon*)
		Photodir=/store_00020001/DCIM/100CANON
		;;
	*Samsung*)
		Photodir=/store_00010001/DCIM/Camera
		read -n1 -p "Select \"Allow\" on phone then press any key"
		;;
	*EOS_DIGITAL*)
		Photodir=/DCIM/100CANON
		;;
	*)
		Photodir=/store_00010001/DCIM
		;;
esac

gphoto2 -f $Photodir --list-files || exit 1

read -p "Do you want to import all pictures from this camera? (y/n) "
printf "\n"
[ "$REPLY" = "n" ] && exit

Tempdir=$(mktemp -d ~/Pictures/tmp.XXXXXX)
cd $Tempdir || exit 1

gphoto2 -f $Photodir --get-all-files

read -p "Do you want to delete all pictures from camera?
	(Type yes if you do, otherwise press enter to keep pictures) "
[ "$REPLY" = yes ] && gphoto2 -f $Photodir --delete-all-files --recurse

printf "\nIt is now safe to unplug the camera\n\n"
sleep 2

photo_rename
video_rename *mp4 && ln -vt ~/Videos *mp4
photo_video_sort

cd ~
rmdir $Tempdir 2>/dev/null && printf "\nDone\n\n" || \
	printf "\nSome files still in Pictures/%s\nto deal with manually\n\n" $Tempdir
read -n1 -p "Press any key to finish"
