#!/bin/sh
#
# /usr/local/bin/photo_rename
#
# Rename photos to YYYYMMDD_HHMMSS.jpg

for i in *.jpg *.JPG; do
	[ -f "$i" ] || continue
	exiv2 -vtF rename "$i" && continue
	Name=""
	Name=$(identify -verbose "$i" | awk -F" " '/exif:DateTimeOriginal:/ { print $2"_"$3".jpg" }' | tr -d ":")
	[ "$Name" ] || \
		Name=$(identify -verbose "$i" | awk -F" " '/exif:DateTime:/ { print $2"_"$3".jpg" }' | tr -d ":")
	[ "$Name" ] || \
		Name=$(identify -verbose "$i" | awk -F" " '/date:modify:/ { print $2"+.jpg" }' | tr T _ | tr -d ":" | tr -d - | cut -d+ -f1,3 --output-delimiter="")
	if [ "$Name" ]; then
		until [ ! -f "$Name" ]; do
			Name="${Name/.jpg/x.jpg}" 
		done
		mv -nv "$i" "$Name" && continue
	fi
	printf "No info in file:  %s\n" "$i" >>~/photo_rename.log
done
