#!/bin/sh
#
# /usr/local/bin/photo_import
#
# Import media from camera
#
# Requires: photo_rename photo_sort video_relink video_sort

Num=$( gphoto2 --auto-detect | wc -l )
if [ $Num -le 2 ]; then
	read -n1 -p "No camera connected
	Press any key to exit "
	exit
fi

gphoto2 --auto-detect | grep -q Samsung && Photodir=/store_00010001/DCIM/Camera
gphoto2 --auto-detect | grep -q EOS_DIGITAL && Photodir=/DCIM/100CANON
Photodir=${Photodir:-/store_00010001/DCIM}

gphoto2 -f $Photodir --list-files || exit 1

read -p "Do you want to import all pictures from this camera? (y/n) "
printf "\n"
[ "$REPLY" = "n" ] && exit

Tempdir=$(mktemp -d ~/Pictures/tmp.XXXXXX)
cd $Tempdir || exit 1

gphoto2 -f $Photodir --get-all-files

read -p "Do you want to delete all pictures from camera?
	(Type yes if you do, otherwise press enter to keep pictures) "
[ "$REPLY" = yes ] && gphoto2 -f $Photodir --delete-all-files --recurse

printf "\nIt is now safe to unplug the camera\n\n"
sleep 2

photo_rename
photo_sort

for i in *.mp4; do
	[ -f "$i" ] || break
	video_rename "$i"
	video_relink "$i"
	video_sort
done

cd ~
rmdir $Tempdir 2>/dev/null && printf "\nDone\n\n" || \
	printf "\nSome files still in Pictures/%s\nto deal with manually\n\n" $Tempdir
read -n1 -p "Press any key to finish"
