#!/bin/sh
#
# /usr/local/bin/photo_import_thunar
#
# Import media from current directory
#
# Requires: photo_rename video_rename photo_video_sort

read -p "Do you want to import all pictures from this folder? (y/n) "
printf "\n"
[ "$REPLY" = "n" ] && exit

Tempdir=$(mktemp -d ~/Pictures/tmp.XXXXXX)

for i in *.jpg *.JPG *.mp4; do
	[ -f "$i" ] && cp -v "$i" $Tempdir
done

read -p "Do you want to delete all pictures from this folder?
	(Type yes if you do, otherwise press enter to keep pictures) "
[ "$REPLY" = yes ] && rm -f *.jpg *.JPG *.mp4

cd $Tempdir || exit 1

photo_rename
video_rename *mp4 && ln -vt ~/Videos *mp4
photo_video_sort

cd ~
rmdir $Tempdir 2>/dev/null && printf "\nDone\n\n" || \
	printf "\nSome files still in Pictures/%s\nto deal with manually\n\n" $Tempdir
read -n1 -p "Press any key to finish"
