#!/bin/sh
#
# /usr/local/bin/photo_import
#
# Import photos from phone, requires photo_rename and photo_sort

set -e

Photodir=""
gphoto2 --auto-detect | grep -q Samsung && Photodir=Camera
gphoto2 -f /store_00010001/DCIM/$Photodir --list-files

read -n1 -p "Do you want to import all pictures from this camera?
	(Press any key to continue or Ctrl-C to exit) "

Tempdir=$(mktemp -d ~/Pictures/tmp.XXXXXX)
cd $Tempdir
gphoto2 -f /store_00010001/DCIM/$Photodir --get-all-files

read -p "Do you want to delete all pictures from camera?
	(Type yes if you do, otherwise press enter to keep pictures) "
[ "$REPLY" = yes ] && \
	gphoto2 -f /store_00010001/DCIM/$Photodir --delete-all-files --recurse

photo_rename
photo_sort

cd ~
rmdir $Tempdir 2>/dev/null && printf "\nDone\n\n" || \
	printf "\nSome photos still in %s\nto deal with manually\n\n" $Tempdir
read -n1 -p "Press any key to finish"
