#!/bin/sh
#
# /usr/local/bin/photo_sort
#
# Sort photos into ~/Pictures/YYYY/MM/

find . -type f | \
while read -r File; do
		Name=$(basename "$File")
		Year="${Name:0:4}"
		Month="${Name:4:2}"
		case $Year in
			20[0-9][0-9])           ;;
			*)             continue ;;
		esac	
		case $Month in
			[0-1][0-9])             ;;
			*)             continue ;;
		esac	
		mkdir -p ~/Pictures/$Year/$Month
		mv -nv "$File" ~/Pictures/$Year/$Month/
done
