#!/bin/sh
#
# /usr/local/bin/photo_import_thunar
#
# Import media from current directory
#
# Requires: photo_rename photo_sort video_relink video_sort

read -p "Do you want to import all pictures from this folder? (y/n) "
[ "$REPLY" = "n" ] && exit
printf "\n"

Tempdir=$(mktemp -d ~/Pictures/tmp.XXXXXX)

for i in *.jpg *.JPG *.mp4; do
	[ -f "$i" ] && cp -v "$i" $Tempdir
done

read -p "Do you want to delete all pictures from this folder?
	(Type yes if you do, otherwise press enter to keep pictures) "
[ "$REPLY" = yes ] && rm -f *.jpg *.JPG *.mp4

cd $Tempdir || exit 1
photo_rename
photo_sort

for i in *.mp4; do
	[ -f "$i" ] || break
	video_rename "$i"
	video_relink "$i"
	video_sort
done

cd ~
rmdir $Tempdir 2>/dev/null && printf "\nDone\n\n" || \
	printf "\nSome files still in Pictures/%s\nto deal with manually\n\n" $Tempdir
read -n1 -p "Press any key to finish"
