#!/bin/sh
#
# /usr/local/bin/player_e17
#
# Depends: dmenu, audacious, mplayer


# If audacious is running, send it a command:
if pgrep audacious >/dev/null; then
    case $1 in
        prev)   audacious --rew
                exit
                ;;
        next)   audacious --fwd
                exit
                ;;
        stop)   audacious --stop
                exit
                ;;
        *)      audacious --play-pause
                exit
                ;;
    esac
fi

# If mplayer is running, send it a command down the pipe:
if pgrep mplayer >/dev/null; then
    case $1 in
        prev)   echo pt_step -1 >~/.mplayer/mp_pipe
                exit
                ;;
        next)   echo pt_step 1 >~/.mplayer/mp_pipe
                exit
                ;;
        stop)   echo stop >~/.mplayer/mp_pipe
                exit
                ;;
        *)      echo pause >~/.mplayer/mp_pipe
                exit
                ;;
    esac
fi

# Only continue if script was invoked with no arguments
[ "$1" ] && exit

# Select an option:
Option=$( printf "Music\nDVD" | dmenu -i -l 2 ) || exit

case "$Option" in
    Music)  exec audacious
            ;;
    DVD)    exec mplayer dvd://
            ;;
    *)      exit
            ;;
esac

