#!/bin/sh
#
# /usr/local/bin/player
#
# Depends: dmenu, mplayer


# If audacious is running, send it a command:
if pgrep audacious >/dev/null; then
    case $1 in
        prev)   audacious --rew
                exit
                ;;
        next)   audacious --fwd
                exit
                ;;
        stop)   audacious --stop
                exit
                ;;
        *)      audacious --play-pause
                exit
                ;;
    esac
fi

# If mplayer is running, send it a command down the pipe:
if pgrep mplayer >/dev/null; then
    case $1 in
        prev)   echo pt_step -1 >~/.mplayer/mp_pipe
                exit
                ;;
        next)   echo pt_step 1 >~/.mplayer/mp_pipe
                exit
                ;;
        stop)   echo stop >~/.mplayer/mp_pipe
                exit
                ;;
        *)      echo pause >~/.mplayer/mp_pipe
                exit
                ;;
    esac
fi

# Only continue if script was invoked with no arguments
[ "$1" ] && exit

# Cache files:
AlbumCache=~/.mplayer/album_cache
TrackCache=~/.mplayer/track_cache

if stest -dlq -n "$AlbumCache" ~/Music; then
    # Update caches if anything has changed:
    printf "Jukebox\nDVD\n" >"$AlbumCache"
    stest -dl ~/Music | sort >>"$AlbumCache"
    stest -f ~/Music/*/* >"$TrackCache"
fi

# Select an album:
Album=$( dmenu <"$AlbumCache" -i -l 40 ) || exit

case "$Album" in
    Jukebox)
        # Prompt for filters:
        Filters=$( dmenu </dev/null -p "Filters?" ) || exit

if [ "$Filters" ]; then
            # Apply filters and shuffle tracks:
            set $( echo "$Filters" )
            for i; do
            grep -Fi "$1" "$TrackCache"
            done | exec mplayer -playlist - -shuffle

        else
            # No filters, so shuffle all tracks:
            exec mplayer -playlist "$TrackCache" -shuffle
        fi
    ;;

    DVD)
        exec mplayer dvd://
    ;;

    *)
        # Album is selected, prompt to play or shuffle:
        Mode=$( printf "Play\nShuffle" | dmenu -i -l 2 ) || exit

if [ "$Mode" = Shuffle ]; then
            # Shuffle album tracks:
            exec mplayer ~/Music/"$Album"/* -shuffle

        else
            # Play album in order:
            exec mplayer ~/Music/"$Album"/*
        fi
    ;;

esac

