#!/bin/sh

# Bind to `Menu' key to launch?

# Select a word
cat /usr/share/dict/words | dmenu | xclip
#cat /usr/share/dict/words | dmenu -l 10 | xclip -selection clip

# Paste it in
#xclip -o
xdotool type $(xclip -o)  # one of these?
#xdotool type $(xsel)  #
