#!/bin/bash
#
# /usr/local/bin/rbackup

Server=rpi
Drive=DATA
Logfile=~/Documents/.rbackup-log
Date=$(date +%Y%m%d)
Hostname=$HOSTNAME

exec > >(tee -a $Logfile) 2>&1

printf "\n#### Starting rbackup script - $(date) ####\n"

printf "Checking DATA drive is mounted... "
ssh $Server mkdir -p $Drive 
ssh $Server mount $Drive
ssh $Server mountpoint -q $Drive && printf "done\n" || \
	{ printf "DATA drive not accessible - exiting\n"; exit 1; }

printf "#### Making rbackup snapshot $Hostname-$Date ####\n"
rsync -aHxv --delete-after \
	--exclude=.cache/ \
	--exclude=.thunderbird/Profiles/$USER.default/ImapMail/ \
	--exclude=.mozilla/firefox/$USER.default/ \
	--exclude="Pictures/2018/04/Samoa-copy"/ \
	--link-dest=../$Hostname \
	~/ $Server:$Drive/$Hostname-$Date

ssh $Server "
	cd $Drive
	rm $Hostname
	ln -sv $Hostname-$Date $Hostname || \
		printf \"linking snapshot $Hostname-$Date failed\" "

printf "\nUnmounting DATA drive... "
ssh $Server umount $Drive
ssh $Server rmdir $Drive && printf "done" 

printf "\nEnd rbackup script - $(date) ####\n"
printf "\n################################################################\n\n"
sleep 1
