#!/bin/sh
#
# sbotool - tool to install, upgrade and search slackbuilds.org packages

Workdir=/tmp/sbotool
Cachefile=/var/cache/SLACKBUILDS.TXT
Arch=$(uname -m)
Release=$(cut -d" " -f2 /etc/slackware-version)

[ $UID -eq 0 ] || exit 1
mkdir -p $Workdir
rm -f $Workdir/{deps,upgrades}

usage () {
	cat <<EOF
sbotool - tool to install, upgrade and search slackbuilds.org packages
Usage:
	sbotool update | upgrade-all
	sbottol search PACKAGE 
	sbotool install | upgrade PACKAGE [...]
EOF
exit 2
}

update () {
	wget -N https://slackbuilds.org/slackbuilds/$Release/SLACKBUILDS.TXT \
		-P /var/cache || exit 3
	printf "SLACKBUILDS.TXT up to date\n\n"
}

search () {
	[ -r $Cachefile ] || update
	grep -F -e "NAME" -e "SHORT DESCRIPTION" $Cachefile | grep -i "$1"
}

install () {
	while [ "$1" ]; do
		export Pkg="$1"
		(
		cd $Workdir
		rm -rf $Workdir/"$Pkg"
		Section=$(grep /"$Pkg"$ $Cachefile | cut -d/ -f2)
		wget https://slackbuilds.org/slackbuilds/$Release/$Section/"$Pkg".tar.gz
		tar xf "$Pkg".tar.gz
		rm "$Pkg".tar.gz
		cd "$Pkg" || exit 4
		. ./"$Pkg".info
		if [ "$REQUIRES" ]; then
			ls -rt /var/log/packages | grep -F SBo | rev | cut -d- -f4- | \
			while read -r Dep; do
				REQUIRES=${REQUIRES/$Dep}
				printf "$REQUIRES\n" >$Workdir/deps
			done
			read -n 1 -p "$Pkg depends on: $(cat $Workdir/deps)
			Install dependencies? Or (e)dit dependency list (y/n/e) "
			printf "\n"
			[ "$REPLY" = n ] && exit 5
			[ "$REPLY" = e ] && ${EDITOR:-vi} $Workdir/deps
			install $(cat $Workdir/deps)
			rm -rf $Workdir/deps
		fi
		if [ "$Arch" = x86_64 ]; then
			wget $DOWNLOAD_x86_64 || wget $DOWNLOAD || exit 6
		else
			wget $DOWNLOAD || exit 6
		fi
		sh ./"$Pkg".SlackBuild || exit 7
		upgradepkg --install-new /tmp/"$Pkg"-$VERSION*.t?z || exit 8
		rm -f /tmp/"$Pkg"-$VERSION*.t?z
		cd ..
		rm -rf $Workdir/"$Pkg"
		)
		shift
	done
}

upgrade_all () {
	rm -f $Workdir/upgrades
	ls -rt /var/log/packages | grep -F SBo | rev | cut -d- -f3- | \
	while read -r Pkg; do
		Name=$(echo $Pkg | cut -d- -f2- | rev)
		Ver=$(echo $Pkg | cut -d- -f1 | rev)
		grep -A2 /$Name$ $Cachefile | grep -q $Ver$ || {
			printf "%s-%s is not up to date\n" $Name $Ver
			printf "%s " $Name >>$Workdir/upgrades
		}
	done
	[ -r $Workdir/upgrades ] || {
		printf "Nothing to update\n\n"; exit 0
	}
	printf "\n"
	read -n 1 -p "Install upgrades? Or (e)dit upgrade list (y/n/e) "
	printf "\n"
	[ "$REPLY" = n ] && exit 9
	[ "$REPLY" = e ] && ${EDITOR:-vi} $Workdir/upgrades
	install $(cat $Workdir/upgrades)
	rm -f $Workdir/upgrades
}

case "$1" in
	update)
		update
		;;
	install | upgrade)
		shift
		install "$@"
		;;
	upgrade-all)
		upgrade_all
		;;
	search)
		search "$2"
		;;
	*)
		usage
		;;
esac

exit 0
