#!/bin/sh
#
# sbotool - tool to install, upgrade and search slackbuilds.org packages

Workdir=/tmp/sbotool
Cachefile=/var/cache/SLACKBUILDS.TXT
Arch=$(uname -m)
Release=$(cut -d" " -f2 /etc/slackware-version)

[ $UID -eq 0 ] || exit 1

usage () {
	cat <<EOF
sbotool - tool to install, upgrade and search slackbuilds.org packages
Usage:
	sbotool update | upgrade-all
	sbottol search PACKAGE 
	sbotool upgrade | install PACKAGE [...]
EOF
exit 2
}

update () {
	rm -f $Cachefile
	wget https://slackbuilds.org/slackbuilds/$Release/SLACKBUILDS.TXT \
		-O $Cachefile || exit 3
	printf "SLACKBUILDS.TXT updated\n\n"
}

search () {
	[ -r $Cachefile ] || update
	grep "SHORT DESCRIPTION" $Cachefile | cut -d" " -f4- | grep -i "$1"
}

upgrade () {
	mkdir -p $Workdir 2>/dev/null
	while [ "$1" ]; do
		export "$1"
		(
		cd $Workdir
		rm -rf $Workdir/"$1"
		Section=$(grep /"$1"$ $Cachefile | cut -d/ -f2)
		wget https://slackbuilds.org/slackbuilds/$Release/$Section/"$1".tar.gz
		tar xf "$1".tar.gz
		rm "$1".tar.gz
		cd "$1" || exit 4
		. ./"$1".info
		if [ "$REQUIRES" ] && [ -z "$Skipdeps" ]; then
			read -n 1 -p "$1 depends on: $REQUIRES
		   	Do you want to install these now? (y/n) "
			[ "$REPLY" = n ] && { printf "\n"; exit 5; }
			upgrade $REQUIRES
		fi
		if [ "$Arch" = x86_64 ]; then
			wget $DOWNLOAD_X86_64 || wget $DOWNLOAD || exit 6
		else
			wget $DOWNLOAD || exit 6
		fi
		sh ./"$1".SlackBuild || exit 7
		upgradepkg --install-new /tmp/"$1"-$VERSION-*.t?z || exit 8
		rm -f /tmp/"$1"-$VERSION-*.t?z
		cd ..
		rm -rf $Workdir/"$1"
		)
		shift
	done
} 
upgrade_all () {
	export Skipdeps=yes
	rm -f $Workdir/upgrades
	ls -rt /var/log/packages | grep SBo | rev | cut -d- -f3- | \
	while read -r Pkg; do
		Name=$(echo $Pkg | cut -d- -f2- | rev)
		Ver=$(echo $Pkg | cut -d- -f1 | rev)
		grep -A2 /$Name$ $Cachefile | grep -q $Ver$ || {
			printf "%s-%s is not up to date\n" $Name $Ver
			printf "%s " $Name >>$Workdir/upgrades
		}
	done
	[ -r $Workdir/upgrades ] || {
		printf "Nothing to update\n\n"; exit 0
	}
	printf "\n"
	read -n 1 -p "Install upgrades? Or (e)dit upgrade list (y/n/e) "
	printf "\n"
	[ "$REPLY" = n ] && exit 9
	[ "$REPLY" = e ] && ${EDITOR:-vi} $Workdir/upgrades
	upgrade $(cat $Workdir/upgrades)
}

case "$1" in
	update)
		update
		;;
	upgrade|install)
		shift
		upgrade "$@"
		;;
	upgrade-all)
		upgrade_all
		;;
	search)
		search "$2"
		;;
	*)
		usage
		;;
esac

exit 0
